"""rename default_golds to medals

Revision ID: 06c5072c76d4
Revises: d41bbff5accf
Create Date: 2025-04-22 23:31:50.418701

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "06c5072c76d4"
down_revision = "d41bbff5accf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "medals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("happened_at", sa.DateTime(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("division_id", sa.UUID(), nullable=False),
        sa.Column("athlete_id", sa.UUID(), nullable=False),
        sa.Column("team_id", sa.UUID(), nullable=False),
        sa.Column("place", sa.Integer(), nullable=False),
        sa.Column("default_gold", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["division_id"],
            ["divisions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("medals", schema=None) as batch_op:
        batch_op.create_index("ix_medals_athlete_id", ["athlete_id"], unique=False)
        batch_op.create_index("ix_medals_division_id", ["division_id"], unique=False)
        batch_op.create_index("ix_medals_event_id", ["event_id"], unique=False)
        batch_op.create_index("ix_medals_happened_at", ["happened_at"], unique=False)
        batch_op.create_index("ix_medals_team_id", ["team_id"], unique=False)

    op.execute(
        """
        INSERT INTO medals (id, happened_at, event_id, division_id, athlete_id, team_id, place, default_gold)
        SELECT id, happened_at, event_id, division_id, athlete_id, team_id, 1, TRUE
        FROM default_golds
        """
    )

    with op.batch_alter_table("default_golds", schema=None) as batch_op:
        batch_op.drop_index("ix_default_golds_athlete_id")
        batch_op.drop_index("ix_default_golds_division_id")
        batch_op.drop_index("ix_default_golds_event_id")
        batch_op.drop_index("ix_default_golds_happened_at")
        batch_op.drop_index("ix_default_golds_team_id")

    op.drop_table("default_golds")

    with op.batch_alter_table("match_participants", schema=None) as batch_op:
        batch_op.drop_column("medal")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("match_participants", schema=None) as batch_op:
        batch_op.add_column(sa.Column("medal", sa.INTEGER(), nullable=True))

    op.create_table(
        "default_golds",
        sa.Column("id", sa.NUMERIC(), nullable=False),
        sa.Column("happened_at", sa.DATETIME(), nullable=False),
        sa.Column("event_id", sa.NUMERIC(), nullable=False),
        sa.Column("division_id", sa.NUMERIC(), nullable=False),
        sa.Column("athlete_id", sa.NUMERIC(), nullable=False),
        sa.Column("team_id", sa.NUMERIC(), nullable=False),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["division_id"],
            ["divisions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("default_golds", schema=None) as batch_op:
        batch_op.create_index("ix_default_golds_team_id", ["team_id"], unique=False)
        batch_op.create_index(
            "ix_default_golds_happened_at", ["happened_at"], unique=False
        )
        batch_op.create_index("ix_default_golds_event_id", ["event_id"], unique=False)
        batch_op.create_index(
            "ix_default_golds_division_id", ["division_id"], unique=False
        )
        batch_op.create_index(
            "ix_default_golds_athlete_id", ["athlete_id"], unique=False
        )

    op.execute(
        """
        INSERT INTO default_golds (id, happened_at, event_id, division_id, athlete_id, team_id)
        SELECT id, happened_at, event_id, division_id, athlete_id, team_id
        FROM medals
        WHERE default_gold = TRUE
        """
    )

    with op.batch_alter_table("medals", schema=None) as batch_op:
        batch_op.drop_index("ix_medals_team_id")
        batch_op.drop_index("ix_medals_happened_at")
        batch_op.drop_index("ix_medals_event_id")
        batch_op.drop_index("ix_medals_division_id")
        batch_op.drop_index("ix_medals_athlete_id")

    op.drop_table("medals")
    # ### end Alembic commands ###
