"""suspend tayane porfirio

Revision ID: 0862fbdb2381
Revises: 4e7a9c1d2b30
Create Date: 2026-09-02 17:42:28.759623

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "0862fbdb2381"
down_revision = "4e7a9c1d2b30"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    connection.execute(
        sa.text(
            "INSERT INTO suspensions (id, athlete_name, start_date, end_date, reason, suspending_org) VALUES "
            "('812274f9-d9e1-4b62-970a-b3bb319c551c', 'Tayane Porfírio de Araújo', '2018-05-30 00:00:00', '2022-06-22 23:59:59', '19‐norandrosterone (19‐NA) and 19-noretiocholanolone', 'USADA'),"
            "('52e783aa-593e-47f6-bf27-806c3addfcbd', 'Tayane Porfírio de Araújo', '2026-05-30 00:00:00', '2026-10-08 23:59:59', 'Carboxy-THC', 'USADA')"
        )
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    connection.execute(
        sa.text(
            "DELETE FROM suspensions WHERE id IN ('812274f9-d9e1-4b62-970a-b3bb319c551c', '52e783aa-593e-47f6-bf27-806c3addfcbd')"
        )
    )
    # ### end Alembic commands ###
