"""add medals only column

Revision ID: 09e07cec375d
Revises: 92048bfbe6a9
Create Date: 2025-11-19 20:38:14.082291

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "09e07cec375d"
down_revision = "92048bfbe6a9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.add_column(sa.Column("medals_only", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_column("medals_only")
    # ### end Alembic commands ###
