"""add match count to ratings table

Revision ID: 119e840a5ba8
Revises: 7d25ab23ef5a
Create Date: 2025-02-20 09:53:24.170291

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "119e840a5ba8"
down_revision = "7d25ab23ef5a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("athlete_ratings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("match_count", sa.Integer(), nullable=True))

    op.execute("UPDATE athlete_ratings SET match_count = 100")

    with op.batch_alter_table("athlete_ratings", schema=None) as batch_op:
        batch_op.alter_column("match_count", existing_type=sa.INTEGER(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("athlete_ratings", schema=None) as batch_op:
        batch_op.drop_column("match_count")

    # ### end Alembic commands ###
