"""add end time for streams

Revision ID: 14c3d5b66ab0
Revises: 4b9aad15cd37
Create Date: 2025-12-05 22:51:39.218842

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "14c3d5b66ab0"
down_revision = "4b9aad15cd37"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("live_streams", schema=None) as batch_op:
        batch_op.add_column(sa.Column("start_seconds", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("end_hour", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("end_minute", sa.Integer(), nullable=True))

    # Set default values for existing rows
    live_streams_table = sa.table(
        "live_streams",
        sa.column("start_seconds", sa.Integer),
        sa.column("end_hour", sa.Integer),
        sa.column("end_minute", sa.Integer),
    )
    op.execute(
        live_streams_table.update()
        .where(live_streams_table.c.start_seconds.is_(None))
        .values(start_seconds=0, end_hour=23, end_minute=0)
    )

    with op.batch_alter_table("live_streams", schema=None) as batch_op:
        batch_op.alter_column(
            "start_seconds",
            existing_type=sa.Integer(),
            nullable=False,
        )
        batch_op.alter_column(
            "end_hour",
            existing_type=sa.Integer(),
            nullable=False,
        )
        batch_op.alter_column(
            "end_minute",
            existing_type=sa.Integer(),
            nullable=False,
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("live_streams", schema=None) as batch_op:
        batch_op.drop_column("end_minute")
        batch_op.drop_column("end_hour")
        batch_op.drop_column("start_seconds")

    # ### end Alembic commands ###
