"""add manual_promotions table

Revision ID: 15a704d921bf
Revises: 515b1aeeedc3
Create Date: 2025-10-26 12:37:35.368957

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "15a704d921bf"
down_revision = "515b1aeeedc3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "manual_promotions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("athlete_id", sa.UUID(), nullable=False),
        sa.Column("belt", sa.String(), nullable=False),
        sa.Column("promoted_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("manual_promotions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_manual_promotions_athlete_id", ["athlete_id"], unique=False
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("manual_promotions", schema=None) as batch_op:
        batch_op.drop_index("ix_manual_promotions_athlete_id")

    op.drop_table("manual_promotions")
    # ### end Alembic commands ###
