"""add profile image saved at column

Revision ID: 162c522eb7ba
Revises: 6c9ba0f0bbb1
Create Date: 2025-10-18 22:09:10.976857

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "162c522eb7ba"
down_revision = "6c9ba0f0bbb1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("athletes", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "profile_image_saved_at",
                postgresql.TIMESTAMP(timezone=True),
                nullable=True,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("athletes", schema=None) as batch_op:
        batch_op.drop_column("profile_image_saved_at")

    # ### end Alembic commands ###
