"""Initial migration

Revision ID: 1aff1f1fccc1
Revises: 
Create Date: 2024-12-19 20:10:11.211937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aff1f1fccc1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('athletes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ibjjf_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ibjjf_id')
    )
    op.create_table('divisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gi', sa.Boolean(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('age', sa.String(), nullable=False),
    sa.Column('belt', sa.String(), nullable=False),
    sa.Column('weight', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ibjjf_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ibjjf_id')
    )
    op.create_table('teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('happened_at', sa.DateTime(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('division_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_index('ix_division_id', ['division_id'], unique=False)
        batch_op.create_index('ix_event_id', ['event_id'], unique=False)

    op.create_table('match_participants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('athlete_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('winner', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('start_rating', sa.Float(), nullable=False),
    sa.Column('end_rating', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match_participants', schema=None) as batch_op:
        batch_op.create_index('ix_athlete_id', ['athlete_id'], unique=False)
        batch_op.create_index('ix_match_id', ['match_id'], unique=False)
        batch_op.create_index('ix_team_id', ['team_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_participants', schema=None) as batch_op:
        batch_op.drop_index('ix_team_id')
        batch_op.drop_index('ix_match_id')
        batch_op.drop_index('ix_athlete_id')

    op.drop_table('match_participants')
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index('ix_event_id')
        batch_op.drop_index('ix_division_id')

    op.drop_table('matches')
    op.drop_table('teams')
    op.drop_table('events')
    op.drop_table('divisions')
    op.drop_table('athletes')
    # ### end Alembic commands ###
