"""add division_id column to live ratings

Revision ID: 2013da636b5e
Revises: 15a704d921bf
Create Date: 2025-11-01 14:29:47.871473

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "2013da636b5e"
down_revision = "15a704d921bf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("live_ratings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("division_id", sa.UUID(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("live_ratings", schema=None) as batch_op:
        batch_op.drop_column("division_id")

    # ### end Alembic commands ###
