"""add drift factor

Revision ID: 24239787850c
Revises: 14c3d5b66ab0
Create Date: 2025-12-07 14:15:44.359189

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "24239787850c"
down_revision = "14c3d5b66ab0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("live_streams", schema=None) as batch_op:
        batch_op.add_column(sa.Column("drift_factor", sa.Float(), nullable=True))

    # Set a default drift factor of 1.0 for existing records
    op.execute("UPDATE live_streams SET drift_factor = 0.998")

    with op.batch_alter_table("live_streams", schema=None) as batch_op:
        batch_op.alter_column("drift_factor", existing_type=sa.Float(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("live_streams", schema=None) as batch_op:
        batch_op.drop_column("drift_factor")

    # ### end Alembic commands ###
