"""add event_id to registration_links

Revision ID: 27d6e8d02377
Revises: 985a6d09f7f2
Create Date: 2025-08-01 20:55:26.638229

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "27d6e8d02377"
down_revision = "985a6d09f7f2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("registration_links", schema=None) as batch_op:
        batch_op.add_column(sa.Column("event_id", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("registration_links", schema=None) as batch_op:
        batch_op.drop_column("event_id")

    # ### end Alembic commands ###
