"""modify registration_link_competitors index

Revision ID: 314ceff88c96
Revises: dd904d7ee108
Create Date: 2025-07-27 15:27:35.731735

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "314ceff88c96"
down_revision = "dd904d7ee108"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("registration_link_competitors", schema=None) as batch_op:
        batch_op.drop_index("ix_registration_link_competitors_all")
        batch_op.create_index(
            "ix_registration_link_competitors_all",
            ["athlete_name", "registration_link_id", "division_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("registration_link_competitors", schema=None) as batch_op:
        batch_op.drop_index("ix_registration_link_competitors_all")
        batch_op.create_index(
            "ix_registration_link_competitors_all",
            ["registration_link_id", "athlete_name"],
            unique=False,
        )

    # ### end Alembic commands ###
