"""add bracket cache

Revision ID: 324d24f6ead6
Revises: e411802c23af
Create Date: 2025-01-26 08:35:49.937157

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "324d24f6ead6"
down_revision = "e411802c23af"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        "bracket_pages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("saved_at", sa.DateTime(), nullable=False),
        sa.Column("link", sa.String(), nullable=False),
        sa.Column("html", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table("bracket_pages")

    # ### end Alembic commands ###
