"""add match_number column

Revision ID: 374fae1b61ba
Revises: 7a2dd4030e8e
Create Date: 2025-04-30 22:11:43.729355

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "374fae1b61ba"
down_revision = "7a2dd4030e8e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("matches", schema=None) as batch_op:
        batch_op.add_column(sa.Column("match_number", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("matches", schema=None) as batch_op:
        batch_op.drop_column("match_number")

    # ### end Alembic commands ###
