"""more suspensions

Revision ID: 418baca5ec40
Revises: a36c83b25da0
Create Date: 2025-12-02 18:50:36.564013

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "418baca5ec40"
down_revision = "a36c83b25da0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("suspensions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("suspending_org", sa.String(), nullable=True))

    connection = op.get_bind()

    connection.execute(
        sa.text(
            "DELETE FROM suspensions WHERE athlete_name IN ('Kaynan Duarte', 'Micael Ferreira Galvão')"
        )
    )
    connection.execute(
        sa.text(
            "INSERT INTO suspensions (id, athlete_name, start_date, end_date, reason, suspending_org) VALUES "
            "('6035c578-d9fe-4dba-9f3d-6a12d4607e87', 'Júlia de Jesus Alves', '2024-02-23 00:00:00', '2027-02-23 23:59:59', 'Oxandrolone', 'UAE NADA'),"
            "('e4f431b5-fbbe-4891-badb-a37e03b6b029', 'Micael Ferreira Galvâo', '2022-07-22 00:00:00', '2023-07-22 23:59:59', 'Clomiphene', 'USADA'),"
            "('2b6d18fa-6d2b-4079-ad77-b9dd84150307', 'Kaynan Casemiro Duarte', '2019-06-02 00:00:00', '2020-06-02 23:59:59', 'Ostarine', 'USADA')"
        )
    )

    connection.execute(
        sa.text(
            "UPDATE suspensions SET suspending_org = 'USADA' WHERE suspending_org IS NULL"
        )
    )

    connection.execute(
        sa.text(
            "UPDATE suspensions SET athlete_name = 'Paulo Henrique Bordignon Miyao' WHERE athlete_name = 'Paulo Miyao'"
        )
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("suspensions", schema=None) as batch_op:
        batch_op.drop_column("suspending_org")
    # ### end Alembic commands ###
