"""add end date index

Revision ID: 424657a063fa
Revises: 64ac6734a825
Create Date: 2025-08-03 21:28:03.986121

"""

from alembic import op


# revision identifiers, used by Alembic.
revision = "424657a063fa"
down_revision = "64ac6734a825"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("registration_links", schema=None) as batch_op:
        batch_op.create_index(
            "ix_registration_links_event_end_date", ["event_end_date"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("registration_links", schema=None) as batch_op:
        batch_op.drop_index("ix_registration_links_event_end_date")

    # ### end Alembic commands ###
