"""fix and rename current_ratings

Revision ID: 437b007233f4
Revises: 69f04669a1a3
Create Date: 2024-12-22 22:41:43.076766

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "437b007233f4"
down_revision = "69f04669a1a3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "athlete_ratings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("athlete_id", sa.UUID(), nullable=False),
        sa.Column("rating", sa.Float(), nullable=False),
        sa.Column("gender", sa.String(), nullable=False),
        sa.Column("age", sa.String(), nullable=False),
        sa.Column("belt", sa.String(), nullable=False),
        sa.Column("gi", sa.Boolean(), nullable=False),
        sa.Column("match_happened_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "athlete_id",
            "gender",
            "age",
            "gi",
            name="uq_athlete_ratings_athlete_gender_age_gi",
        ),
    )
    with op.batch_alter_table("athlete_ratings", schema=None) as batch_op:
        batch_op.create_index(
            "ix_athlete_ratings_all", ["gender", "age", "belt", "gi"], unique=False
        )
        batch_op.create_index(
            "ix_athlete_ratings_athlete_id", ["athlete_id"], unique=False
        )
        batch_op.create_index("ix_athlete_ratings_rating", ["rating"], unique=False)

    with op.batch_alter_table("current_ratings", schema=None) as batch_op:
        batch_op.drop_index("ix_current_ratings_all")
        batch_op.drop_index("ix_current_ratings_athlete_id")
        batch_op.drop_index("ix_current_ratings_rating")

    op.drop_table("current_ratings")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        "current_ratings",
        sa.Column("athlete_id", sa.UUID(), nullable=False),
        sa.Column("rating", sa.FLOAT(), nullable=False),
        sa.Column("gender", sa.VARCHAR(), nullable=False),
        sa.Column("age", sa.VARCHAR(), nullable=False),
        sa.Column("belt", sa.VARCHAR(), nullable=False),
        sa.Column("gi", sa.BOOLEAN(), nullable=False),
        sa.Column("match_happened_at", sa.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
        ),
        sa.PrimaryKeyConstraint("athlete_id"),
    )
    with op.batch_alter_table("current_ratings", schema=None) as batch_op:
        batch_op.create_index("ix_current_ratings_rating", ["rating"], unique=False)
        batch_op.create_index(
            "ix_current_ratings_athlete_id", ["athlete_id"], unique=False
        )
        batch_op.create_index(
            "ix_current_ratings_all", ["gender", "age", "belt", "gi"], unique=False
        )

    with op.batch_alter_table("athlete_ratings", schema=None) as batch_op:
        batch_op.drop_index("ix_athlete_ratings_rating")
        batch_op.drop_index("ix_athlete_ratings_athlete_id")
        batch_op.drop_index("ix_athlete_ratings_all")

    op.drop_table("athlete_ratings")
    # ### end Alembic commands ###
