"""add flo event tags table

Revision ID: 4b9aad15cd37
Revises: ce02b112a731
Create Date: 2025-12-04 22:18:30.017465

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "4b9aad15cd37"
down_revision = "ce02b112a731"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "flo_event_tags",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.String(), nullable=False),
        sa.Column("tag", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("flo_event_tags", schema=None) as batch_op:
        batch_op.create_index("ix_flo_event_tags_event_id", ["event_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("flo_event_tags", schema=None) as batch_op:
        batch_op.drop_index("ix_flo_event_tags_event_id")

    op.drop_table("flo_event_tags")
    # ### end Alembic commands ###
