"""add live_ratings table

Revision ID: 4f9189dbab12
Revises: 424657a063fa
Create Date: 2025-08-30 23:37:19.147007

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4f9189dbab12"
down_revision = "424657a063fa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "live_ratings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("athlete_id", sa.UUID(), nullable=False),
        sa.Column("rating", sa.Float(), nullable=False),
        sa.Column("match_count", sa.Integer(), nullable=False),
        sa.Column("gi", sa.Boolean(), nullable=False),
        sa.Column("happened_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("live_ratings", schema=None) as batch_op:
        batch_op.create_index(
            "ix_live_ratings_athlete_id", ["athlete_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("live_ratings", schema=None) as batch_op:
        batch_op.drop_index("ix_live_ratings_athlete_id")

    op.drop_table("live_ratings")
    # ### end Alembic commands ###
