"""add personal name column

Revision ID: 515b1aeeedc3
Revises: 162c522eb7ba
Create Date: 2025-10-22 01:08:56.336231

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "515b1aeeedc3"
down_revision = "162c522eb7ba"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("athletes", schema=None) as batch_op:
        batch_op.add_column(sa.Column("personal_name", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("athletes", schema=None) as batch_op:
        batch_op.drop_column("personal_name")

    # ### end Alembic commands ###
