"""add bjjheroes column

Revision ID: 5de767d1e8f0
Revises: 675a43460ef2
Create Date: 2025-12-16 19:45:13.749354

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "5de767d1e8f0"
down_revision = "675a43460ef2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("athletes", schema=None) as batch_op:
        batch_op.add_column(sa.Column("bjjheroes_link", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("athletes", schema=None) as batch_op:
        batch_op.drop_column("bjjheroes_link")

    # ### end Alembic commands ###
