"""add instagram column

Revision ID: 5f538a761c4b
Revises: 4f9189dbab12
Create Date: 2025-08-31 21:49:21.014445

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5f538a761c4b"
down_revision = "4f9189dbab12"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("athletes", schema=None) as batch_op:
        batch_op.add_column(sa.Column("instagram_profile", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("athletes", schema=None) as batch_op:
        batch_op.drop_column("instagram_profile")

    # ### end Alembic commands ###
