"""add event_start_date index

Revision ID: 64ac6734a825
Revises: 27d6e8d02377
Create Date: 2025-08-03 17:03:44.078441

"""

from alembic import op


# revision identifiers, used by Alembic.
revision = "64ac6734a825"
down_revision = "27d6e8d02377"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("registration_links", schema=None) as batch_op:
        batch_op.create_index(
            "ix_registration_links_event_start_date", ["event_start_date"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("registration_links", schema=None) as batch_op:
        batch_op.drop_index("ix_registration_links_event_start_date")

    # ### end Alembic commands ###
