"""add hide_all column

Revision ID: 675a43460ef2
Revises: 24239787850c
Create Date: 2025-12-10 20:41:53.316804

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "675a43460ef2"
down_revision = "24239787850c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("live_streams", schema=None) as batch_op:
        batch_op.add_column(sa.Column("hide_all", sa.Boolean(), nullable=True))

    op.execute("UPDATE live_streams SET hide_all = false")

    with op.batch_alter_table("live_streams", schema=None) as batch_op:
        batch_op.alter_column("hide_all", existing_type=sa.Boolean(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("live_streams", schema=None) as batch_op:
        batch_op.drop_column("hide_all")

    # ### end Alembic commands ###
