"""Initial migration

Revision ID: 69f04669a1a3
Revises:
Create Date: 2024-12-20 23:00:58.350290

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "69f04669a1a3"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "athletes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("ibjjf_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ibjjf_id"),
    )
    with op.batch_alter_table("athletes", schema=None) as batch_op:
        batch_op.create_index("ix_athletes_ibjjf_id", ["ibjjf_id"], unique=False)
        batch_op.create_index("ix_athletes_name", ["name"], unique=False)

    op.create_table(
        "divisions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("gi", sa.Boolean(), nullable=False),
        sa.Column("gender", sa.String(), nullable=False),
        sa.Column("age", sa.String(), nullable=False),
        sa.Column("belt", sa.String(), nullable=False),
        sa.Column("weight", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("divisions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_divisions_all", ["gi", "gender", "age", "belt", "weight"], unique=False
        )

    op.create_table(
        "events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("ibjjf_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ibjjf_id"),
    )
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.create_index("ix_events_ibjjf_id", ["ibjjf_id"], unique=False)
        batch_op.create_index("ix_events_name", ["name"], unique=False)

    op.create_table(
        "teams",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("teams", schema=None) as batch_op:
        batch_op.create_index("ix_teams_name", ["name"], unique=False)

    op.create_table(
        "current_ratings",
        sa.Column("athlete_id", sa.UUID(), nullable=False),
        sa.Column("rating", sa.Float(), nullable=False),
        sa.Column("gender", sa.String(), nullable=False),
        sa.Column("age", sa.String(), nullable=False),
        sa.Column("belt", sa.String(), nullable=False),
        sa.Column("gi", sa.Boolean(), nullable=False),
        sa.Column("match_happened_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
        ),
        sa.PrimaryKeyConstraint("athlete_id"),
    )
    with op.batch_alter_table("current_ratings", schema=None) as batch_op:
        batch_op.create_index(
            "ix_current_ratings_all", ["gender", "age", "belt", "gi"], unique=False
        )
        batch_op.create_index(
            "ix_current_ratings_athlete_id", ["athlete_id"], unique=False
        )
        batch_op.create_index("ix_current_ratings_rating", ["rating"], unique=False)

    op.create_table(
        "matches",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("happened_at", sa.DateTime(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("division_id", sa.UUID(), nullable=False),
        sa.Column("rated", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["division_id"],
            ["divisions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("matches", schema=None) as batch_op:
        batch_op.create_index("ix_matches_division_id", ["division_id"], unique=False)
        batch_op.create_index("ix_matches_event_id", ["event_id"], unique=False)
        batch_op.create_index("ix_matches_happened_at", ["happened_at"], unique=False)

    op.create_table(
        "match_participants",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("match_id", sa.UUID(), nullable=False),
        sa.Column("athlete_id", sa.UUID(), nullable=False),
        sa.Column("team_id", sa.UUID(), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("red", sa.Boolean(), nullable=False),
        sa.Column("winner", sa.Boolean(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("start_rating", sa.Float(), nullable=False),
        sa.Column("end_rating", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
        ),
        sa.ForeignKeyConstraint(["match_id"], ["matches.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("match_participants", schema=None) as batch_op:
        batch_op.create_index(
            "ix_match_participants_athlete_id", ["athlete_id"], unique=False
        )
        batch_op.create_index(
            "ix_match_participants_match_id", ["match_id"], unique=False
        )
        batch_op.create_index(
            "ix_match_participants_team_id", ["team_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("match_participants", schema=None) as batch_op:
        batch_op.drop_index("ix_match_participants_team_id")
        batch_op.drop_index("ix_match_participants_match_id")
        batch_op.drop_index("ix_match_participants_athlete_id")

    op.drop_table("match_participants")
    with op.batch_alter_table("matches", schema=None) as batch_op:
        batch_op.drop_index("ix_matches_happened_at")
        batch_op.drop_index("ix_matches_event_id")
        batch_op.drop_index("ix_matches_division_id")

    op.drop_table("matches")
    with op.batch_alter_table("current_ratings", schema=None) as batch_op:
        batch_op.drop_index("ix_current_ratings_rating")
        batch_op.drop_index("ix_current_ratings_athlete_id")
        batch_op.drop_index("ix_current_ratings_all")

    op.drop_table("current_ratings")
    with op.batch_alter_table("teams", schema=None) as batch_op:
        batch_op.drop_index("ix_teams_name")

    op.drop_table("teams")
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_index("ix_events_name")
        batch_op.drop_index("ix_events_ibjjf_id")

    op.drop_table("events")
    with op.batch_alter_table("divisions", schema=None) as batch_op:
        batch_op.drop_index("ix_divisions_all")

    op.drop_table("divisions")
    with op.batch_alter_table("athletes", schema=None) as batch_op:
        batch_op.drop_index("ix_athletes_name")
        batch_op.drop_index("ix_athletes_ibjjf_id")

    op.drop_table("athletes")
    # ### end Alembic commands ###
