"""add athlete slugs

Revision ID: 6bbe1ba31ac5
Revises: ce94040ebf50
Create Date: 2025-11-03 09:03:37.636762

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "6bbe1ba31ac5"
down_revision = "ce94040ebf50"
branch_labels = None
depends_on = None

suffixes = {"jr", "sr", "ii", "iii", "iv"}


def generate_slug_raw_sql(connection, table, normalized_name: str) -> str:
    words = normalized_name.split()

    if len(words) > 1 and words[-1] in suffixes:
        words = words[:-1]

    if len(words) > 1 and words[-1] in suffixes:
        words = words[:-1]

    if len(words) == 0:
        base_slug = "athlete"
    else:
        base_slug = "-".join([words[0], words[-1]])

    slug = base_slug
    count = 1
    unique_index = 2

    # Check for uniqueness and modify slug if necessary
    while (
        connection.execute(
            sa.text(f"SELECT 1 FROM {table} WHERE slug = :slug"),
            {"slug": slug},
        ).first()
        is not None
    ):
        if len(words) > 2 and count < len(words) - 1:
            # Add middle names one by one
            slug = "-".join([words[0]] + words[1 : count + 1] + [words[-1]])
            count += 1
        else:
            # Append a number to the slug
            slug = f"{base_slug}-{unique_index}"
            unique_index += 1

    return slug


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("athletes", schema=None) as batch_op:
        batch_op.add_column(sa.Column("slug", sa.String(), nullable=True))
        batch_op.create_unique_constraint("uq_athlete_slug", ["slug"])

    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.add_column(sa.Column("slug", sa.String(), nullable=True))
        batch_op.create_unique_constraint("uq_event_slug", ["slug"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_constraint("uq_event_slug", type_="unique")
        batch_op.drop_column("slug")

    with op.batch_alter_table("athletes", schema=None) as batch_op:
        batch_op.drop_constraint("uq_athlete_slug", type_="unique")
        batch_op.drop_column("slug")

    # ### end Alembic commands ###
