"""add country column

Revision ID: 6c9ba0f0bbb1
Revises: 5f538a761c4b
Create Date: 2025-09-14 00:22:53.621441

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6c9ba0f0bbb1"
down_revision = "5f538a761c4b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("athletes", schema=None) as batch_op:
        batch_op.add_column(sa.Column("country", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("country_note", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("country_note_pt", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("athletes", schema=None) as batch_op:
        batch_op.drop_column("country_note_pt")
        batch_op.drop_column("country_note")
        batch_op.drop_column("country")

    # ### end Alembic commands ###
