"""add tsvector columns

Revision ID: 6fbd5fa2b92b
Revises: 8904720248bd
Create Date: 2025-11-08 19:21:26.250673

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "6fbd5fa2b92b"
down_revision = "8904720248bd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    dialect = bind.dialect.name
    with op.batch_alter_table("athletes", schema=None) as batch_op:
        batch_op.create_index(
            "ix_athletes_normalized_personal_name_covering",
            ["normalized_personal_name", "id"],
            unique=False,
        )
        if dialect == "postgresql":
            batch_op.add_column(
                sa.Column(
                    "normalized_name_tsvector", postgresql.TSVECTOR(), nullable=True
                )
            )
            batch_op.add_column(
                sa.Column(
                    "normalized_personal_name_tsvector",
                    postgresql.TSVECTOR(),
                    nullable=True,
                )
            )
            batch_op.create_index(
                "ix_athletes_normalized_name_tsvector",
                ["normalized_name_tsvector"],
                unique=False,
                postgresql_using="gin",
            )
            batch_op.create_index(
                "ix_athletes_normalized_personal_name_tsvector",
                ["normalized_personal_name_tsvector"],
                unique=False,
                postgresql_using="gin",
            )

            batch_op.execute(
                """
                CREATE OR REPLACE FUNCTION update_athlete_tsvectors() RETURNS trigger AS $$
                BEGIN
                NEW.normalized_name_tsvector := to_tsvector('simple', NEW.normalized_name);
                NEW.normalized_personal_name_tsvector := to_tsvector('simple', NEW.normalized_personal_name);
                RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;
            """
            )
            batch_op.execute(
                """
                CREATE TRIGGER athlete_tsvector_update
                BEFORE INSERT OR UPDATE ON athletes
                FOR EACH ROW EXECUTE FUNCTION update_athlete_tsvectors();
            """
            )
        else:
            batch_op.add_column(
                sa.Column("normalized_name_tsvector", sa.VARCHAR(), nullable=True)
            )
            batch_op.add_column(
                sa.Column(
                    "normalized_personal_name_tsvector", sa.VARCHAR(), nullable=True
                )
            )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    dialect = bind.dialect.name

    with op.batch_alter_table("athletes", schema=None) as batch_op:
        batch_op.drop_index("ix_athletes_normalized_personal_name_covering")
        if dialect == "postgresql":
            batch_op.execute(
                "DROP TRIGGER IF EXISTS athlete_tsvector_update ON athletes;"
            )
            batch_op.execute("DROP FUNCTION IF EXISTS update_athlete_tsvectors();")
            batch_op.drop_index(
                "ix_athletes_normalized_personal_name_tsvector", postgresql_using="gin"
            )
            batch_op.drop_index(
                "ix_athletes_normalized_name_tsvector", postgresql_using="gin"
            )
        batch_op.drop_column("normalized_personal_name_tsvector")
        batch_op.drop_column("normalized_name_tsvector")
    # ### end Alembic commands ###
