"""add name mapping tables

Revision ID: 705a14243635
Revises: 759ee3416ccc
Create Date: 2026-03-14 10:42:17.151709

"""

from alembic import op
import sqlalchemy as sa
import uuid


# revision identifiers, used by Alembic.
revision = "705a14243635"
down_revision = "759ee3416ccc"
branch_labels = None
depends_on = None

FLO_SEARCH_NAME_MAPPINGS = [
    ("Andy Tomas Murasaki Pereira", "Andy Murasaki", None),
    ("Erich Munis dos Santos", "Erich Munis", None),
    ("Pedro Henrique Pinheiro M. de Souza", "Pedro Machado", None),
    ("Jackson Nagai Hatchwell Junior", "Jackson Nagai", None),
    (
        "Edwin Ocasio",
        "Ocasio",
        "inconsistent, sometimes Junny Ocasio sometimes Edwin Ocasio or Edwin Junny Ocasio",
    ),
    ("Matheus Vetoraci de Menezes", "Matheus Vetoraci", None),
    ("Davi Vetoraci de Menezes", "Davi Vetoraci", None),
    ("William James Wilson", "Will Wilson", None),
    ("Victor Hugo Costa Marques", "Victor Hugo", None),
]

TEAM_NAME_MAPPINGS = [
    ("Atos JJ International", "Atos Jiu-Jitsu"),
    ("Atos JJ USA", "Atos Jiu-Jitsu"),
    ("Art of Jiu Jitsu", "AOJ"),
    ("Art of Jiu-Jitsu", "AOJ"),
    ("Caio Terra Association", "Brasa CTA"),
    ("Caio Terra Association Brasil", "Brasa CTA"),
    ("Brasa Poland", "Brasa CTA"),
    ("Cicero Costha Internacional", "PSLPB Cicero Costha"),
    ("Cicero Costha Europe", "PSLPB Cicero Costha"),
    ("GFTeam - Jiu Art", "GF Team"),
    ("PSLPB Cicero Costha USA", "PSLPB Cicero Costha"),
    ("Fratres Jiu Jitsu Competition", "Fratres Brazilian Jiu-Jitsu"),
    ("Fratres Chile Jiu-Jitsu", "Fratres Brazilian Jiu-Jitsu"),
    ("DreamArt", "Dream Art"),
    ("DreamArt Houston", "Dream Art"),
    ("DreamArt Conroe", "Dream Art"),
    ("Guigo BJJ", "Guigo JJ"),
    ("Infight JJ", "Infight Jiu-Jitsu"),
    ("Checkmat Dallas - Keiser Girao", "CheckMat"),
    ("Marcio Andre Association", "Marcio Andre Jiu-Jitsu"),
    ("Melqui Galvão Jiu-jitsu", "Melqui Galvão BJJ"),
    ("NS Brotherhood International", "Ns Brotherhood"),
    ("NU/Nova União", "Nova União"),
    ("Lotus Club Criciúma / SC", "Lótus Club"),
    ("Alliance*", "Alliance"),
    ("AOJ*", "AOJ"),
    ("Ares BJJ*", "Ares BJJ"),
    ("Atos Jiu-Jitsu*", "Atos Jiu-Jitsu"),
    ("Brazilian Top Team*", "Brazilian Top Team"),
    ("CheckMat*", "CheckMat"),
    ("Fight Sports*", "Fight Sports"),
    ("Gracie Barra*", "Gracie Barra"),
    ("Ns Brotherhood*", "Ns Brotherhood"),
    ("Ryan Gracie Team*", "Ryan Gracie Team"),
    ("Nova União*", "Nova União"),
    ("ZR Team*", "ZR Team"),
    ("Gracie Humaita*", "Gracie Humaita"),
]


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "flo_search_names",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("athlete_name", sa.String(), nullable=False),
        sa.Column("search_name", sa.String(), nullable=False),
        sa.Column("comment", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("flo_search_names", schema=None) as batch_op:
        batch_op.create_index(
            "ix_flo_search_names_athlete_name", ["athlete_name"], unique=False
        )

    op.create_table(
        "team_name_mappings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name_match", sa.String(), nullable=False),
        sa.Column("mapped_name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    flo_search_names = sa.table(
        "flo_search_names",
        sa.column("id", sa.UUID()),
        sa.column("athlete_name", sa.String()),
        sa.column("search_name", sa.String()),
        sa.column("comment", sa.String()),
    )
    op.bulk_insert(
        flo_search_names,
        [
            {
                "id": uuid.uuid4(),
                "athlete_name": athlete_name,
                "search_name": search_name,
                "comment": comment,
            }
            for athlete_name, search_name, comment in FLO_SEARCH_NAME_MAPPINGS
        ],
    )

    team_name_mappings = sa.table(
        "team_name_mappings",
        sa.column("id", sa.UUID()),
        sa.column("name_match", sa.String()),
        sa.column("mapped_name", sa.String()),
    )
    op.bulk_insert(
        team_name_mappings,
        [
            {
                "id": uuid.uuid4(),
                "name_match": name_match,
                "mapped_name": mapped_name,
            }
            for name_match, mapped_name in TEAM_NAME_MAPPINGS
        ],
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("team_name_mappings")

    with op.batch_alter_table("flo_search_names", schema=None) as batch_op:
        batch_op.drop_index("ix_flo_search_names_athlete_name")

    op.drop_table("flo_search_names")
    # ### end Alembic commands ###
