"""add live_streams table

Revision ID: 705b423bdf49
Revises: 418baca5ec40
Create Date: 2025-12-02 20:11:43.430978

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "705b423bdf49"
down_revision = "418baca5ec40"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "live_streams",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.String(), nullable=False),
        sa.Column("platform", sa.String(), nullable=False),
        sa.Column("mat_number", sa.Integer(), nullable=False),
        sa.Column("day_number", sa.Integer(), nullable=False),
        sa.Column("start_hour", sa.Integer(), nullable=False),
        sa.Column("start_minute", sa.Integer(), nullable=False),
        sa.Column("link", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("live_streams", schema=None) as batch_op:
        batch_op.create_index("ix_live_streams_event_id", ["event_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("live_streams", schema=None) as batch_op:
        batch_op.drop_index("ix_live_streams_event_id")

    op.drop_table("live_streams")
    # ### end Alembic commands ###
