"""add bg tasks

Revision ID: 759ee3416ccc
Revises: c98fb3816ed0
Create Date: 2026-01-27 20:14:05.882480

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "759ee3416ccc"
down_revision = "c98fb3816ed0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        "background_tasks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("task_type", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("params_json", sa.Text(), nullable=True),
        sa.Column("log_text", sa.Text(), nullable=True),
        sa.Column("exit_code", sa.Integer(), nullable=True),
        sa.Column("pid", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("background_tasks", schema=None) as batch_op:
        batch_op.create_index(
            "ix_background_tasks_created_at", ["created_at"], unique=False
        )
        batch_op.create_index("ix_background_tasks_status", ["status"], unique=False)
        batch_op.create_index("ix_background_tasks_type", ["task_type"], unique=False)
        batch_op.create_index("ix_background_tasks_pid", ["pid"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("background_tasks", schema=None) as batch_op:
        batch_op.drop_index("ix_background_tasks_type")
        batch_op.drop_index("ix_background_tasks_status")
        batch_op.drop_index("ix_background_tasks_created_at")

    op.drop_table("background_tasks")

    # ### end Alembic commands ###
