"""add indexes to bracket pages

Revision ID: 7a2dd4030e8e
Revises: 06c5072c76d4
Create Date: 2025-04-23 20:38:55.875450

"""

from alembic import op


# revision identifiers, used by Alembic.
revision = "7a2dd4030e8e"
down_revision = "06c5072c76d4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("bracket_pages", schema=None) as batch_op:
        batch_op.create_index("ix_bracket_pages_link", ["link"], unique=False)
        batch_op.create_index("ix_bracket_pages_saved_at", ["saved_at"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("bracket_pages", schema=None) as batch_op:
        batch_op.drop_index("ix_bracket_pages_saved_at")
        batch_op.drop_index("ix_bracket_pages_link")

    # ### end Alembic commands ###
