"""remove nullable

Revision ID: 7aa5615a64b0
Revises: 6bbe1ba31ac5
Create Date: 2025-11-03 19:49:03.060264

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7aa5615a64b0"
down_revision = "6bbe1ba31ac5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("athletes", schema=None) as batch_op:
        batch_op.alter_column("slug", existing_type=sa.VARCHAR(), nullable=False)

    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.alter_column("slug", existing_type=sa.VARCHAR(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.alter_column("slug", existing_type=sa.VARCHAR(), nullable=True)

    with op.batch_alter_table("athletes", schema=None) as batch_op:
        batch_op.alter_column("slug", existing_type=sa.VARCHAR(), nullable=True)

    # ### end Alembic commands ###
