"""add start/end match counts

Revision ID: 7d25ab23ef5a
Revises: 91b89628d467
Create Date: 2025-02-20 09:33:17.816528

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7d25ab23ef5a"
down_revision = "91b89628d467"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("match_participants", schema=None) as batch_op:
        batch_op.alter_column("match_count", new_column_name="start_match_count")
        batch_op.add_column(sa.Column("end_match_count", sa.Integer(), nullable=True))

    op.execute(
        """UPDATE match_participants SET end_match_count = CASE
            WHEN (select rated from matches where id = match_participants.match_id) AND (
                (select NOT rated_winner_only from matches where id = match_participants.match_id)
                OR
                (winner)
            ) THEN start_match_count + 1
            ELSE start_match_count
        END"""
    )

    with op.batch_alter_table("match_participants", schema=None) as batch_op:
        batch_op.alter_column(
            "end_match_count", existing_type=sa.INTEGER(), nullable=False
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("match_participants", schema=None) as batch_op:
        batch_op.drop_column("end_match_count")
        batch_op.alter_column("start_match_count", new_column_name="match_count")

    # ### end Alembic commands ###
