"""rename personal name and add normalized column

Revision ID: 8904720248bd
Revises: 7aa5615a64b0
Create Date: 2025-11-08 08:34:49.126799

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8904720248bd"
down_revision = "7aa5615a64b0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("athletes", schema=None) as batch_op:
        batch_op.alter_column(
            "instagram_profile_personal_name", new_column_name="personal_name"
        )
        batch_op.add_column(
            sa.Column("normalized_personal_name", sa.String(), nullable=True)
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("athletes", schema=None) as batch_op:
        batch_op.drop_column("normalized_personal_name")
        batch_op.alter_column(
            "personal_name", new_column_name="instagram_profile_personal_name"
        )
    # ### end Alembic commands ###
