"""add nickname translation column

Revision ID: 8c055d2ba4d0
Revises: 09e07cec375d
Create Date: 2025-11-30 17:59:27.202931

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "8c055d2ba4d0"
down_revision = "09e07cec375d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("athletes", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("nickname_translation", sa.String(), nullable=True)
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("athletes", schema=None) as batch_op:
        batch_op.drop_column("nickname_translation")
    # ### end Alembic commands ###
