"""add match_count column

Revision ID: 91b89628d467
Revises: eb621719b23f
Create Date: 2025-02-19 09:37:00.623142

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "91b89628d467"
down_revision = "eb621719b23f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("match_participants", schema=None) as batch_op:
        batch_op.add_column(sa.Column("match_count", sa.Integer(), nullable=True))

    op.execute(
        """UPDATE match_participants SET match_count = (
                    SELECT COUNT(*) FROM match_participants mp
                    JOIN matches m ON mp.match_id = m.id
                    JOIN divisions d ON m.division_id = d.id
                    WHERE mp.athlete_id = match_participants.athlete_id
                    AND (m.rated AND ((NOT m.rated_winner_only) OR mp.winner))
                    AND d.gi = (SELECT gi FROM divisions JOIN matches ON divisions.id = matches.division_id WHERE matches.id = match_participants.match_id)
                    AND m.happened_at < (SELECT happened_at FROM matches WHERE id = match_participants.match_id)
              )"""
    )

    with op.batch_alter_table("match_participants", schema=None) as batch_op:
        batch_op.alter_column("match_count", existing_type=sa.INTEGER(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("match_participants", schema=None) as batch_op:
        batch_op.drop_column("match_count")

    # ### end Alembic commands ###
