"""add team name to registration_link_competitors

Revision ID: 92048bfbe6a9
Revises: 6fbd5fa2b92b
Create Date: 2025-11-13 12:33:04.348427

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "92048bfbe6a9"
down_revision = "6fbd5fa2b92b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("registration_link_competitors", schema=None) as batch_op:
        batch_op.add_column(sa.Column("team_name", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("registration_link_competitors", schema=None) as batch_op:
        batch_op.drop_column("team_name")

    # ### end Alembic commands ###
