"""add event start and end dates

Revision ID: 985a6d09f7f2
Revises: 314ceff88c96
Create Date: 2025-07-28 21:03:40.519961

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "985a6d09f7f2"
down_revision = "314ceff88c96"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("registration_links", schema=None) as batch_op:
        batch_op.add_column(sa.Column("event_start_date", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("event_end_date", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("registration_links", schema=None) as batch_op:
        batch_op.drop_column("event_end_date")
        batch_op.drop_column("event_start_date")

    # ### end Alembic commands ###
