"""add reason column

Revision ID: a36c83b25da0
Revises: 8c055d2ba4d0
Create Date: 2025-11-30 23:39:28.316982

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "a36c83b25da0"
down_revision = "8c055d2ba4d0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("suspensions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("reason", sa.String(), nullable=True))

    # delete existing data
    op.execute("DELETE FROM suspensions")

    # insert updated data with reason column
    insert_statement = """INSERT INTO suspensions (id, athlete_name, start_date, end_date, reason) VALUES
    ('bf05fe40-864f-4b34-9443-cc9ba0682873', 'Pedro Alex dos Santos Pimenta', '2024-06-01 00:00:00', '2025-07-12 23:59:59', 'Clomiphene'),
    ('41c0a143-ed72-4c50-9c2d-f2d03ef20b37', 'Yatan Martins Bueno', '2024-06-02 00:00:00', '2027-07-12 23:59:59', '19-Norandrosterone'),
    ('39744869-0d04-40aa-9765-07b3d2b1dcdf', 'Fellipe Andrew Leandro Silva', '2024-03-24 00:00:00', '2026-04-16 23:59:59', 'Clomiphene'),
    ('e8e3b404-ed16-45e5-8bbe-1e9b6721f680', 'Uanderson Ferreira de Oliveira', '2024-03-23 00:00:00', '2024-07-17 23:59:59', 'Cannabinoids'),
    ('42bf2d41-a6ea-49f9-96f2-d6789d1a2b14', 'Micael Ferreira Galvão', '2022-06-04 00:00:00', '2023-07-22 23:59:59', 'Clomiphene'),
    ('f8094023-34a6-4182-a30d-f8562bebe083', 'André Luiz Novaes Porfirio', '2022-12-11 00:00:00', '2027-03-21 23:59:59', 'Androgenic Anabolic Steroid; Non-Analytical: Refusal to Submit to Sample Collection'),
    ('3ea1dbb2-2f48-4fba-8895-37755c20ded4', 'Vagner S. Rocha', '2022-12-11 00:00:00', '2026-01-11 23:59:59', 'Non-Analytical: Refusal to Submit to Sample Collection'),
    ('b6b25d4f-d40c-4ab9-adc2-ea0de21c82b8', 'Igor Nascimento da Costa Feliz', '2022-12-11 00:00:00', '2026-01-24 23:59:59', 'Testosterone'),
    ('757c8a5c-be3f-49b5-b090-3b7330fa5976', 'Jonnatas Gracie Araujo da Silva', '2022-12-11 00:00:00', '2026-01-25 23:59:59', '19-norandrosterone (19-NA); Testosterone'),
    ('135e88aa-73fe-49fc-9ab1-dd35e034e91f', 'Roberto de Abreu Filho', '2022-12-10 00:00:00', '2026-01-27 23:59:59', 'Testosterone'),
    ('903ef9c6-5a02-4f8b-bc12-c222efb2fe9c', 'José Henrique Cardoso', '2022-12-10 00:00:00', '2026-02-01 23:59:59', '19-norandrosterone (19-NA); 2a-methyl-5a-androstan-3a-ol-17-one; Epitrenbolone; Methasterone; Testosterone'),
    ('716b9475-ac73-4937-83b0-44b902f16d56', 'Cássio Felipe Sousa Costa', '2024-12-13 00:00:00', '2025-12-30 23:59:59', 'Clomiphene'),
    ('8a6937fe-37fe-4c2e-bab1-fc1735dc64af', 'Francisco de Assis Lemos Lo', '2025-03-22 00:00:00', '2028-04-28 23:59:59', 'Dehydrochloromethyltestosterone (DHCMT); 19-norandrosterone (19-NA)'),
    ('e2e55bba-7bd1-418e-b6f6-765bb9b7386a', 'Braulio Estima', '2014-11-25 00:00:00', '2016-11-25 23:59:59', 'Methylhexaneamine'),
    ('4a4afe7d-178a-456c-bfff-f8d9dd0ba6bc', 'Felipe Pena', '2015-05-26 00:00:00', '2016-05-26 23:59:59', 'Androgenic Anabolic Steroid'),
    ('12288b8a-2650-4012-90cd-2f20d2696608', 'Leonardo Pires Nogueira', '2015-03-27 00:00:00', '2017-03-27 23:59:59', 'Clomiphene'),
    ('81505198-02bd-4045-9209-28f1aa777252', 'Paulo Miyao', '2015-05-10 00:00:00', '2017-05-10 23:59:59', 'Clomiphene'),
    ('401c4db2-2e01-4747-badb-f3748f63c1e6', 'Tayane Porfirio de Araùjo', '2015-05-10 00:00:00', '2019-05-10 23:59:59', '19‐norandrosterone (19‐NA), 19-noretiocholanolone'),
    ('8ad16830-d181-4c47-b042-6dc441cfb358', 'Kaynan Duarte', '2020-02-07 00:00:00', '202-02-07 23:59:59', 'Ostarine');
    """

    op.execute(insert_statement)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("suspensions", schema=None) as batch_op:
        batch_op.drop_column("reason")

    # ### end Alembic commands ###
