"""add indexes

Revision ID: bbc2b9cc8af2
Revises: 600df6b529e8
Create Date: 2025-03-29 21:50:24.655842

"""

from alembic import op


# revision identifiers, used by Alembic.
revision = "bbc2b9cc8af2"
down_revision = "600df6b529e8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("match_participants", schema=None) as batch_op:
        batch_op.create_index(
            "ix_match_participants_match_id_covering",
            ["match_id", "athlete_id", "id"],
            unique=False,
        )

    with op.batch_alter_table("matches", schema=None) as batch_op:
        batch_op.create_index(
            "ix_matches_division_id_covering", ["division_id", "id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("matches", schema=None) as batch_op:
        batch_op.drop_index("ix_matches_division_id_covering")

    with op.batch_alter_table("match_participants", schema=None) as batch_op:
        batch_op.drop_index("ix_match_participants_match_id_covering")

    # ### end Alembic commands ###
