"""add news analytics

Revision ID: c98fb3816ed0
Revises: 5de767d1e8f0
Create Date: 2026-01-08 20:17:41.782266

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "c98fb3816ed0"
down_revision = "5de767d1e8f0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "news_views_daily",
        sa.Column("post_id", sa.BigInteger(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("views", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("post_id", "day"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("news_views_daily")
    # ### end Alembic commands ###
