"""add mat and fight numbers to matches

Revision ID: cc4b8d60e913
Revises: e2c7b9c9f616
Create Date: 2025-07-19 16:38:42.909606

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cc4b8d60e913"
down_revision = "e2c7b9c9f616"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("matches", schema=None) as batch_op:
        batch_op.add_column(sa.Column("match_location", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("fight_number", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("matches", schema=None) as batch_op:
        batch_op.drop_column("fight_number")
        batch_op.drop_column("match_location")

    # ### end Alembic commands ###
