"""add video link column

Revision ID: ce02b112a731
Revises: 705b423bdf49
Create Date: 2025-12-03 18:38:33.360181

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "ce02b112a731"
down_revision = "705b423bdf49"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("matches", schema=None) as batch_op:
        batch_op.add_column(sa.Column("video_link", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("matches", schema=None) as batch_op:
        batch_op.drop_column("video_link")

    # ### end Alembic commands ###
