"""add percentile and average ranks

Revision ID: ce94040ebf50
Revises: 2013da636b5e
Create Date: 2025-11-02 08:11:05.658344

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "ce94040ebf50"
down_revision = "2013da636b5e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        "athlete_rating_averages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("gender", sa.String(), nullable=False),
        sa.Column("age", sa.String(), nullable=False),
        sa.Column("belt", sa.String(), nullable=False),
        sa.Column("gi", sa.Boolean(), nullable=False),
        sa.Column("weight", sa.String(), nullable=True),
        sa.Column("avg_rating", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "gender",
            "age",
            "belt",
            "gi",
            "weight",
            name="uq_athlete_rating_averages_all",
        ),
    )
    with op.batch_alter_table("athlete_ratings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("percentile", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("previous_percentile", sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("athlete_ratings", schema=None) as batch_op:
        batch_op.drop_column("previous_percentile")
        batch_op.drop_column("percentile")

    op.drop_table("athlete_rating_averages")

    # ### end Alembic commands ###
