"""add medal column

Revision ID: d41bbff5accf
Revises: 4cd95d1d7d55
Create Date: 2025-04-22 22:05:22.754504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd41bbff5accf'
down_revision = '4cd95d1d7d55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('match_participants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('medal', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('match_participants', schema=None) as batch_op:
        batch_op.drop_column('medal')

    # ### end Alembic commands ###
