"""add hide name column

Revision ID: dc06d1a5a17b
Revises: 705a14243635
Create Date: 2026-03-26 23:55:41.063502

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dc06d1a5a17b"
down_revision = "705a14243635"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("athletes", schema=None) as batch_op:
        batch_op.add_column(sa.Column("hide_full_name", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("athletes", schema=None) as batch_op:
        batch_op.drop_column("hide_full_name")

    # ### end Alembic commands ###
