"""add registration_link_competitors table

Revision ID: dd904d7ee108
Revises: feba73c0f085
Create Date: 2025-07-26 20:33:44.852637

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dd904d7ee108"
down_revision = "feba73c0f085"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "registration_link_competitors",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("registration_link_id", sa.UUID(), nullable=False),
        sa.Column("athlete_name", sa.String(), nullable=False),
        sa.Column("division_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["division_id"],
            ["divisions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["registration_link_id"], ["registration_links.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("registration_link_competitors", schema=None) as batch_op:
        batch_op.create_index(
            "ix_registration_link_competitors_all",
            ["registration_link_id", "athlete_name", "division_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("registration_link_competitors", schema=None) as batch_op:
        batch_op.drop_index("ix_registration_link_competitors_all")

    op.drop_table("registration_link_competitors")

    # ### end Alembic commands ###
