"""suspend francisco lo

Revision ID: e2c7b9c9f616
Revises: 6e514f9ccfeb
Create Date: 2025-06-24 17:33:18.901758

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e2c7b9c9f616"
down_revision = "6e514f9ccfeb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    connection.execute(
        sa.text(
            "INSERT INTO suspensions (id, athlete_name, start_date, end_date) VALUES "
            "('8a6937fe-37fe-4c2e-bab1-fc1735dc64af', 'Francisco de Assis Lemos Lo', '2025-03-22 00:00:00', '2028-04-28 23:59:59')"
        )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    connection.execute(
        sa.text(
            "DELETE from suspensions where id = '8a6937fe-37fe-4c2e-bab1-fc1735dc64af'"
        )
    )
    # ### end Alembic commands ###
