"""add previous rating/rank

Revision ID: e411802c23af
Revises: 0ce49eea986a
Create Date: 2025-01-20 20:04:02.228598

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e411802c23af"
down_revision = "0ce49eea986a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("athlete_ratings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("previous_rating", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("previous_rank", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("athlete_ratings", schema=None) as batch_op:
        batch_op.drop_column("previous_rank")
        batch_op.drop_column("previous_rating")

    # ### end Alembic commands ###
