"""add previous_match_count column

Revision ID: e4dfc67c1880
Revises: 119e840a5ba8
Create Date: 2025-03-11 22:17:48.617769

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e4dfc67c1880"
down_revision = "119e840a5ba8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("athlete_ratings", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("previous_match_count", sa.Integer(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("athlete_ratings", schema=None) as batch_op:
        batch_op.drop_column("previous_match_count")

    # ### end Alembic commands ###
