"""add hidden flag to links

Revision ID: feba73c0f085
Revises: cc4b8d60e913
Create Date: 2025-07-26 20:21:26.519542

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "feba73c0f085"
down_revision = "cc4b8d60e913"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("registration_links", schema=None) as batch_op:
        batch_op.add_column(sa.Column("hidden", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("registration_links", schema=None) as batch_op:
        batch_op.drop_column("hidden")

    # ### end Alembic commands ###
