export const countryNames: Record<string, string> = {
  'af': 'Afghanistan',
  'al': 'Albania',
  'am': 'Armenia',
  'ao': 'Angola',
  'ar': 'Argentina',
  'at': 'Austria',
  'au': 'Australia',
  'az': 'Azerbaijan',
  'ba': 'Bosnia and Herzegovina',
  'bb': 'Barbados',
  'bd': 'Bangladesh',
  'be': 'Belgium',
  'bf': 'Burkina Faso',
  'bg': 'Bulgaria',
  'bh': 'Bahrain',
  'bi': 'Burundi',
  'bj': 'Benin',
  'bn': 'Brunei',
  'bo': 'Bolivia',
  'br': 'Brazil',
  'bs': 'Bahamas',
  'bt': 'Bhutan',
  'bw': 'Botswana',
  'by': 'Belarus',
  'bz': 'Belize',
  'ca': 'Canada',
  'cd': 'Democratic Republic of the Congo',
  'cf': 'Central African Republic',
  'cg': 'Congo',
  'ch': 'Switzerland',
  'ci': 'Ivory Coast',
  'cl': 'Chile',
  'cm': 'Cameroon',
  'cn': 'China',
  'co': 'Colombia',
  'cr': 'Costa Rica',
  'cu': 'Cuba',
  'cv': 'Cape Verde',
  'cy': 'Cyprus',
  'cz': 'Czech Republic',
  'de': 'Germany',
  'dj': 'Djibouti',
  'dk': 'Denmark',
  'dm': 'Dominica',
  'do': 'Dominican Republic',
  'dz': 'Algeria',
  'ec': 'Ecuador',
  'ee': 'Estonia',
  'eg': 'Egypt',
  'er': 'Eritrea',
  'es': 'Spain',
  'et': 'Ethiopia',
  'fi': 'Finland',
  'fj': 'Fiji',
  'fm': 'Micronesia',
  'fr': 'France',
  'ga': 'Gabon',
  'gb': 'United Kingdom',
  'gd': 'Grenada',
  'ge': 'Georgia',
  'gh': 'Ghana',
  'gm': 'Gambia',
  'gn': 'Guinea',
  'gq': 'Equatorial Guinea',
  'gr': 'Greece',
  'gt': 'Guatemala',
  'gw': 'Guinea-Bissau',
  'gy': 'Guyana',
  'hk': 'Hong Kong',
  'hn': 'Honduras',
  'hr': 'Croatia',
  'ht': 'Haiti',
  'hu': 'Hungary',
  'id': 'Indonesia',
  'ie': 'Ireland',
  'il': 'Israel',
  'in': 'India',
  'iq': 'Iraq',
  'ir': 'Iran',
  'is': 'Iceland',
  'it': 'Italy',
  'jm': 'Jamaica',
  'jo': 'Jordan',
  'jp': 'Japan',
  'ke': 'Kenya',
  'kg': 'Kyrgyzstan',
  'kh': 'Cambodia',
  'ki': 'Kiribati',
  'km': 'Comoros',
  'kn': 'Saint Kitts and Nevis',
  'kp': 'North Korea',
  'kr': 'South Korea',
  'kw': 'Kuwait',
  'kz': 'Kazakhstan',
  'la': 'Laos',
  'lb': 'Lebanon',
  'lc': 'Saint Lucia',
  'li': 'Liechtenstein',
  'lk': 'Sri Lanka',
  'lr': 'Liberia',
  'ls': 'Lesotho',
  'lt': 'Lithuania',
  'lu': 'Luxembourg',
  'lv': 'Latvia',
  'ly': 'Libya',
  'ma': 'Morocco',
  'mc': 'Monaco',
  'md': 'Moldova',
  'me': 'Montenegro',
  'mg': 'Madagascar',
  'mh': 'Marshall Islands',
  'mk': 'North Macedonia',
  'ml': 'Mali',
  'mm': 'Myanmar',
  'mn': 'Mongolia',
  'mo': 'Macau',
  'mp': 'Northern Mariana Islands',
  'mr': 'Mauritania',
  'mt': 'Malta',
  'mu': 'Mauritius',
  'mv': 'Maldives',
  'mw': 'Malawi',
  'mx': 'Mexico',
  'my': 'Malaysia',
  'mz': 'Mozambique',
  'na': 'Namibia',
  'ne': 'Niger',
  'ng': 'Nigeria',
  'ni': 'Nicaragua',
  'nl': 'Netherlands',
  'no': 'Norway',
  'np': 'Nepal',
  'nr': 'Nauru',
  'nz': 'New Zealand',
  'om': 'Oman',
  'pa': 'Panama',
  'pe': 'Peru',
  'pf': 'French Polynesia',
  'pg': 'Papua New Guinea',
  'ph': 'Philippines',
  'pk': 'Pakistan',
  'pl': 'Poland',
  'pr': 'Puerto Rico',
  'pt': 'Portugal',
  'pw': 'Palau',
  'py': 'Paraguay',
  'qa': 'Qatar',
  'ro': 'Romania',
  'rs': 'Serbia',
  'ru': 'Russia',
  'rw': 'Rwanda',
  'sa': 'Saudi Arabia',
  'sb': 'Solomon Islands',
  'sc': 'Seychelles',
  'sd': 'Sudan',
  'se': 'Sweden',
  'sg': 'Singapore',
  'sh': 'Saint Helena',
  'si': 'Slovenia',
  'sk': 'Slovakia',
  'sl': 'Sierra Leone',
  'sm': 'San Marino',
  'sn': 'Senegal',
  'so': 'Somalia',
  'sr': 'Suriname',
  'ss': 'South Sudan',
  'st': 'Sao Tome and Principe',
  'sv': 'El Salvador',
  'sy': 'Syria',
  'sz': 'Eswatini',
  'tc': 'Turks and Caicos Islands',
  'td': 'Chad',
  'tg': 'Togo',
  'th': 'Thailand',
  'tj': 'Tajikistan',
  'tl': 'Timor-Leste',
  'tm': 'Turkmenistan',
  'tn': 'Tunisia',
  'to': 'Tonga',
  'tr': 'Turkey',
  'tt': 'Trinidad and Tobago',
  'tv': 'Tuvalu',
  'tz': 'Tanzania',
  'ua': 'Ukraine',
  'ug': 'Uganda',
  'uk': 'United Kingdom',
  'us': 'United States',
  'uy': 'Uruguay',
  'uz': 'Uzbekistan',
  'va': 'Vatican City',
  'vc': 'Saint Vincent and the Grenadines',
  've': 'Venezuela',
  'vg': 'British Virgin Islands',
  'vn': 'Vietnam',
  'vu': 'Vanuatu',
  'ws': 'Samoa',
  'ye': 'Yemen',
  'za': 'South Africa',
  'zm': 'Zambia',
  'zw': 'Zimbabwe',
};

export const countryNamesPt: Record<string, string> = {
  'af': 'Afeganistão',
  'al': 'Albânia',
  'am': 'Armênia',
  'ao': 'Angola',
  'ar': 'Argentina',
  'at': 'Áustria',
  'au': 'Austrália',
  'az': 'Azerbaijão',
  'ba': 'Bósnia e Herzegovina',
  'bb': 'Barbados',
  'bd': 'Bangladesh',
  'be': 'Bélgica',
  'bf': 'Burquina Faso',
  'bg': 'Bulgária',
  'bh': 'Bahrein',
  'bi': 'Burundi',
  'bj': 'Benin',
  'bn': 'Brunei',
  'bo': 'Bolívia',
  'br': 'Brasil',
  'bs': 'Bahamas',
  'bt': 'Butão',
  'bw': 'Botsuana',
  'by': 'Bielorrússia',
  'bz': 'Belize',
  'ca': 'Canadá',
  'cd': 'República Democrática do Congo',
  'cf': 'República Centro-Africana',
  'cg': 'Congo',
  'ch': 'Suíça',
  'ci': 'Costa do Marfim',
  'cl': 'Chile',
  'cm': 'Camarões',
  'cn': 'China',
  'co': 'Colômbia',
  'cr': 'Costa Rica',
  'cu': 'Cuba',
  'cv': 'Cabo Verde',
  'cy': 'Chipre',
  'cz': 'República Tcheca',
  'de': 'Alemanha',
  'dj': 'Djibuti',
  'dk': 'Dinamarca',
  'dm': 'Dominica',
  'do': 'República Dominicana',
  'dz': 'Argélia',
  'ec': 'Equador',
  'ee': 'Estônia',
  'eg': 'Egito',
  'er': 'Eritreia',
  'es': 'Espanha',
  'et': 'Etiópia',
  'fi': 'Finlândia',
  'fj': 'Fiji',
  'fm': 'Micronésia',
  'fr': 'França',
  'ga': 'Gabão',
  'gb': 'Reino Unido',
  'gd': 'Granada',
  'ge': 'Geórgia',
  'gh': 'Gana',
  'gm': 'Gâmbia',
  'gn': 'Guiné',
  'gq': 'Guiné Equatorial',
  'gr': 'Grécia',
  'gt': 'Guatemala',
  'gw': 'Guiné-Bissau',
  'gy': 'Guiana',
  'hk': 'Hong Kong',
  'hn': 'Honduras',
  'hr': 'Croácia',
  'ht': 'Haiti',
  'hu': 'Hungria',
  'id': 'Indonésia',
  'ie': 'Irlanda',
  'il': 'Israel',
  'in': 'Índia',
  'iq': 'Iraque',
  'ir': 'Irã',
  'is': 'Islândia',
  'it': 'Itália',
  'jm': 'Jamaica',
  'jo': 'Jordânia',
  'jp': 'Japão',
  'ke': 'Quênia',
  'kg': 'Quirguistão',
  'kh': 'Camboja',
  'ki': 'Quiribati',
  'km': 'Comores',
  'kn': 'São Cristóvão e Nevis',
  'kp': 'Coreia do Norte',
  'kr': 'Coreia do Sul',
  'kw': 'Kuwait',
  'kz': 'Cazaquistão',
  'la': 'Laos',
  'lb': 'Líbano',
  'lc': 'Santa Lúcia',
  'li': 'Liechtenstein',
  'lk': 'Sri Lanka',
  'lr': 'Libéria',
  'ls': 'Lesoto',
  'lt': 'Lituânia',
  'lu': 'Luxemburgo',
  'lv': 'Letônia',
  'ly': 'Líbia',
  'ma': 'Marrocos',
  'mc': 'Mônaco',
  'md': 'Moldávia',
  'me': 'Montenegro',
  'mg': 'Madagáscar',
  'mh': 'Ilhas Marshall',
  'mk': 'Macedônia do Norte',
  'ml': 'Mali',
  'mm': 'Mianmar',
  'mn': 'Mongólia',
  'mo': 'Macau',
  'mp': 'Ilhas Marianas do Norte',
  'mr': 'Mauritânia',
  'mt': 'Malta',
  'mu': 'Maurício',
  'mv': 'Maldivas',
  'mw': 'Maláui',
  'mx': 'México',
  'my': 'Malásia',
  'mz': 'Moçambique',
  'na': 'Namíbia',
  'ne': 'Níger',
  'ng': 'Nigéria',
  'ni': 'Nicarágua',
  'nl': 'Países Baixos',
  'no': 'Noruega',
  'np': 'Nepal',
  'nr': 'Nauru',
  'nz': 'Nova Zelândia',
  'om': 'Omã',
  'pa': 'Panamá',
  'pe': 'Peru',
  'pf': 'Polinésia Francesa',
  'pg': 'Papua-Nova Guiné',
  'ph': 'Filipinas',
  'pk': 'Paquistão',
  'pl': 'Polônia',
  'pr': 'Porto Rico',
  'pt': 'Portugal',
  'pw': 'Palau',
  'py': 'Paraguai',
  'qa': 'Catar',
  'ro': 'Romênia',
  'rs': 'Sérvia',
  'ru': 'Rússia',
  'rw': 'Ruanda',
  'sa': 'Arábia Saudita',
  'sb': 'Ilhas Salomão',
  'sc': 'Seicheles',
  'sd': 'Sudão',
  'se': 'Suécia',
  'sg': 'Singapura',
  'sh': 'Santa Helena',
  'si': 'Eslovênia',
  'sk': 'Eslováquia',
  'sl': 'Serra Leoa',
  'sm': 'San Marino',
  'sn': 'Senegal',
  'so': 'Somália',
  'sr': 'Suriname',
  'ss': 'Sudão do Sul',
  'st': 'São Tomé e Príncipe',
  'sv': 'El Salvador',
  'sy': 'Síria',
  'sz': 'Essuatíni',
  'tc': 'Ilhas Turcas e Caicos',
  'td': 'Chade',
  'tg': 'Togo',
  'th': 'Tailândia',
  'tj': 'Tajiquistão',
  'tl': 'Timor-Leste',
  'tm': 'Turcomenistão',
  'tn': 'Tunísia',
  'to': 'Tonga',
  'tr': 'Turquia',
  'tt': 'Trinidad e Tobago',
  'tv': 'Tuvalu',
  'tz': 'Tanzânia',
  'ua': 'Ucrânia',
  'ug': 'Uganda',
  'uk': 'Reino Unido',
  'us': 'Estados Unidos',
  'uy': 'Uruguai',
  'uz': 'Uzbequistão',
  'va': 'Cidade do Vaticano',
  'vc': 'São Vicente e Granadinas',
  've': 'Venezuela',
  'vg': 'Ilhas Virgens Britânicas',
  'vn': 'Vietnã',
  'vu': 'Vanuatu',
  'ws': 'Samoa',
  'ye': 'Iêmen',
  'za': 'África do Sul',
  'zm': 'Zâmbia',
  'zw': 'Zimbábue',
};
